######################################################################
#
# File name : counter_tb.udo
# Created on: Wed Feb 01 14:09:33 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
