######################################################################
#
# File name : counter_tb_compile.do
# Created on: Wed Feb 01 14:14:43 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Tool\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
D:\\Tool\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

D:\\Tool\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\Tool\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\Tool\\modeltech64_10.6d\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../counter.srcs/sources_1/new/counter.sv" \
"../../../../counter.srcs/sim_1/new/counter_tb.sv" \


# compile glbl module
D:\\Tool\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

