######################################################################
#
# File name : counter_tb_wave.do
# Created on: Wed Feb 01 14:09:33 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
