######################################################################
#
# File name : counter_tb_simulate.do
# Created on: Wed Feb 01 14:14:45 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.counter_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {counter_tb_wave.do}

view wave
view structure
view signals

do {counter_tb.udo}

run 1000ns
