######################################################################
#
# File name : full_add_tb_compile.do
# Created on: Wed Feb 01 11:17:38 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Tool\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
D:\\Tool\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

D:\\Tool\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\Tool\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\Tool\\modeltech64_10.6d\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../add.srcs/sources_1/new/full_add.sv" \
"../../../../add.srcs/sources_1/new/half_add.sv" \
"../../../../add.srcs/sim_1/new/full_add_tb.sv" \


# compile glbl module
D:\\Tool\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

