######################################################################
#
# File name : full_add_tb.udo
# Created on: Wed Feb 01 11:17:40 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
