######################################################################
#
# File name : half_add_tb.udo
# Created on: Tue Jan 31 22:34:19 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
