######################################################################
#
# File name : half_add_tb_wave.do
# Created on: Tue Jan 31 22:34:19 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
